# Generated by Django 5.0.4 on 2024-04-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='price_ticket',
        ),
    ]
