# Generated by Django 5.0.4 on 2024-04-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_date_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price_ticket',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
