# Generated by Django 5.0.4 on 2024-12-11 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_ticket_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_tickets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price_ticket',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tickets_sold',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='type_event',
            field=models.CharField(choices=[('Festa', 'Festa'), ('Reunião', 'Reunião')], max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_images', to='events.event')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_type', to='events.tickettype'),
            preserve_default=False,
        ),
    ]
