# Generated by Django 5.0.4 on 2024-12-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventimage_type_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='amount_sold',
            field=models.IntegerField(default=0),
        ),
    ]
