# Generated by Django 5.0.4 on 2024-04-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0002_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
